import "./assets/css/main.css";
import "./assets/css/basic.css";
import "./assets/css/autoplay.css";
import "./assets/css/thumbnail.css";
import "./assets/css/loop.css";
import "./modules/basic.js";
import "./modules/autoplay.js";
import "./modules/thumbnail.js";
import "./modules/loop.js";